[phases.setup]
nixpkgs = ["python311", "pip"]  # Using Python 3.11 with Pip

[phases.build]
commands = [
  "pip install --upgrade pip",  # Upgrade pip to ensure no compatibility issues
  "pip install -r requirements.txt",  # Install all dependencies including Gunicorn
  "python manage.py collectstatic --noinput"  # Collect static files (if needed)
]

[phases.start]
commands = [
  "gunicorn lorcana.wsgi:application --bind 0.0.0.0:$PORT"  # Start the app using Gunicorn
]
