[phases.setup]
commands = [
  "pip install -r requirements.txt"
]

[phases.build]
commands = [
  "python manage.py collectstatic --noinput"
]

[phases.start]
commands = [
  "gunicorn lorcana.wsgi:application --bind 0.0.0.0:$PORT"
]
