[phases.setup]
nixpkgs = ["python311", "pip"]

[phases.build]
commands = [
  "python -m venv venv",  # Create a virtual environment
  ". venv/bin/activate",  # Activate the virtual environment
  "pip install --upgrade pip",  # Upgrade pip
  "pip install -r requirements.txt",  # Install all dependencies
  "python manage.py collectstatic --noinput"  # Collect static files (if necessary)
]

[phases.start]
commands = [
  ". venv/bin/activate",  # Ensure virtual environment is activated
  "gunicorn lorcana.wsgi:application --bind 0.0.0.0:$PORT"  # Start app with Gunicorn
]
