# Generated by Django 4.1.1 on 2024-10-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_card_created_at_remove_card_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ink',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
